### ISSUE TITLE
FEATURE: SSO introduction

### ISSUE THREAD

**Issue by Segelzwerg** [Whist-Team/Whist-Server#121]
Implement an integration for a Single Sign-On service like Keycloak or an online version like Google, GitHub, etc.

The benefit is that users can use existing registration somewhere to authenticate for this application.

**Comment by abant07** [comment]
Hi @Segelzwerg 

I was wondering if I could recieve more information for this issue?

Thanks

**Comment by Segelzwerg** [comment]
@abant07 I updated the description, let me know, if more information are required or something is not clear.

**Comment by abant07** [comment]
Hi @Segelzwerg 

So just to make sure I am clear on the issue, do I need to create a function that applies a Single-Sign-On to authenticate users on different devices or platforms. If that is the case, should I write this in the user/auth.py file? Also, do you know what resources I should look at first to learn more about Single Sign On, because I don;t exactly know what it is and how it can be used in code?

Thanks

**Comment by abant07** [comment]
Also, where would I receive the existing registration the user gives?

**Comment by Segelzwerg** [comment]
Dear @abant07 with due respect, I think this issue is not solved that easily. We tried but we could get it to work.

**Comment by iTitus** [comment]
In the long term we might want to replace password based login with Google/Apple/Microsoft/GitHub based SSO
